destination: "_site"
timezone: "America/New York"
port: 4000
exclude: [.gitignore, post_template.md, README.md, publish.sh]
permalink: "/:year/:title.html"
defaults:
  -
    scope:
      path: ""
    values:
      type: "post"
      layout: "post"
      author: "The YACS Dev Team"
